- name: Create docker config directory
  file:
    path: /root/.docker
    state: directory

- name: Copy docker config
  copy:
    content: |
      {
        "auths": {
          "incidentes.azurecr.io": {
            "auth": "{{ docker_config_auth }}"
          }
        }
      }
    dest: /root/.docker/config.json