- name: Create /containers folder
  file:
    path: /containers
    state: directory
    mode: '777'
    recurse: yes

- name: Create /containers/redis
  file:
    path: /containers/redis
    state: directory
    mode: '777'
    recurse: yes

- name: Create /containers/postgres
  file: 
    path: '/containers/redis'
    state: directory
    mode: '777'
    recurse: yes

- name: Create /containers/wireguard
  file:
    path: '/containers/wireguard'
    state: directory
    mode: '777'
    recurse: yes

- name: Create /containers/incident-api
  file:
    path: '/containers/incident-api'
    state: directory
    mode: '777'
    recurse: yes